// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsWebapiTrial.Data;

namespace StudentsWebapiTrial.Migrations
{
    [DbContext(typeof(StudentDetailsDBContext))]
    partial class StudentDetailsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentsWebapiTrial.Models.StudentDetails", b =>
                {
                    b.Property<int>("StudID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StudAge")
                        .HasColumnType("int");

                    b.Property<string>("StudCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudID");

                    b.ToTable("dbStudentDetails");

                    b.HasData(
                        new
                        {
                            StudID = 1,
                            StudAge = 12,
                            StudCity = "CTC",
                            StudName = "Samu"
                        },
                        new
                        {
                            StudID = 2,
                            StudAge = 19,
                            StudCity = "ZAQ",
                            StudName = "Dhamu"
                        },
                        new
                        {
                            StudID = 3,
                            StudAge = 13,
                            StudCity = "TWQ",
                            StudName = "Ramu"
                        },
                        new
                        {
                            StudID = 4,
                            StudAge = 15,
                            StudCity = "BBSR",
                            StudName = "Pamu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
